// Code generated by mockery v2.35.2. DO NOT EDIT.

package bitwarden

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Mockclient is an autogenerated mock type for the client type
type Mockclient struct {
	mock.Mock
}

type Mockclient_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockclient) EXPECT() *Mockclient_Expecter {
	return &Mockclient_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: req
func (_m *Mockclient) Do(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockclient_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type Mockclient_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *http.Request
func (_e *Mockclient_Expecter) Do(req interface{}) *Mockclient_Do_Call {
	return &Mockclient_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *Mockclient_Do_Call) Run(run func(req *http.Request)) *Mockclient_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *Mockclient_Do_Call) Return(_a0 *http.Response, _a1 error) *Mockclient_Do_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockclient_Do_Call) RunAndReturn(run func(*http.Request) (*http.Response, error)) *Mockclient_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockclient creates a new instance of Mockclient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockclient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockclient {
	mock := &Mockclient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
